### ISSUE TITLE
{{#each pages}}

### ISSUE THREAD

**Issue by brandonmerritt** [r4fx/mate#1]
I'm using Assemble 0.6.0 too and noticed you and I are having the same issue with the {{#each ...}} in the HB templates. Did you ever find a solution? I spent a few hours yesterday and have nothing to show for it. If I figure it out I'll let you know.

**Comment by r4fx** [comment]
I gave up after a few hours, if you find a way let me know :) THX!

**Comment by brandonmerritt** [comment]
I wound up creating a helper. I still don't think it's the Assemble way but this allows me to create a "friendly name", "tagging" and generate a "friendly url".

```
assemble.data(paths.templates.data);
//Creating the Sitemap JSON
gulp.task('sitemap', function(){
  return gulp.src('./src/*.hbs')
    .pipe(frontMatter({property: 'meta'}))
    .pipe(data(function(file){
      file.meta.url = '../'+ path.basename(file.path, '.hbs') + '/index.html'
     }))
    .pipe(pluck('meta', 'sitemap.json'))
    .pipe(data(function(file){
      file.contents = new Buffer(JSON.stringify(file.meta))
    }))
    .pipe(gulp.dest(paths.build.www))
})
```
